// Smoke placeholder for the default Flutter widget test slot.
//
// The original `Counter increments smoke test` was generated by
// `flutter create` and does not match this app's entry widget. Real widget
// tests live under `test/features/**` and exercise individual blocs/screens
// with their dependencies stubbed.

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('smoke placeholder', () {
    expect(1 + 1, 2);
  });
}
