import 'dart:convert';

import '../../domain/entities/activity_log.dart';

/// Activity log model with JSON serialization

class ActivityLogModel extends ActivityLog {
  const ActivityLogModel({
    required super.id,
    required super.sellerProfileId,
    required super.userId,
    required super.actionType,
    required super.description,
    super.metadata,
    required super.createdAt,
    super.actorName,
    super.actorAvatarUrl,
  });

  factory ActivityLogModel.fromJson(Map<String, dynamic> json) {
    // Parse metadata from JSONB
    Map<String, dynamic>? metadata;
    if (json['metadata'] != null) {
      if (json['metadata'] is String) {
        metadata =
            Map<String, dynamic>.from(jsonDecode(json['metadata'] as String));
      } else if (json['metadata'] is Map) {
        metadata = Map<String, dynamic>.from(json['metadata'] as Map);
      }
    }

    return ActivityLogModel(
      id: json['id'] as String,
      sellerProfileId: json['seller_profile_id'] as String,
      userId: json['user_id'] as String,
      actionType:
          ActivityType.fromString(json['action_type'] as String? ?? ''),
      description: json['description'] as String? ?? '',
      metadata: metadata,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : DateTime.now(),
      actorName: json['actor']?['full_name'] as String?,
      actorAvatarUrl: json['actor']?['avatar_url'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'seller_profile_id': sellerProfileId,
      'user_id': userId,
      'action_type': actionType.value,
      'description': description,
      if (metadata != null) 'metadata': metadata,
      'created_at': createdAt.toIso8601String(),
    };
  }

  /// Create insert payload (without id, created_at — auto-generated by DB)
  Map<String, dynamic> toInsertJson() {
    return {
      'seller_profile_id': sellerProfileId,
      'user_id': userId,
      'action_type': actionType.value,
      'description': description,
      if (metadata != null) 'metadata': metadata,
    };
  }

  factory ActivityLogModel.fromEntity(ActivityLog entity) {
    return ActivityLogModel(
      id: entity.id,
      sellerProfileId: entity.sellerProfileId,
      userId: entity.userId,
      actionType: entity.actionType,
      description: entity.description,
      metadata: entity.metadata,
      createdAt: entity.createdAt,
      actorName: entity.actorName,
      actorAvatarUrl: entity.actorAvatarUrl,
    );
  }
}
