import '../../../../core/services/permission_service.dart';
import '../../domain/entities/seller_member.dart';

/// Seller member model with JSON serialization

class SellerMemberModel extends SellerMember {
  const SellerMemberModel({
    required super.id,
    required super.sellerProfileId,
    required super.userId,
    required super.role,
    super.customPermissions,
    super.invitedBy,
    super.invitedAt,
    super.joinedAt,
    required super.isActive,
    required super.memberName,
    super.memberEmail,
    super.memberAvatarUrl,
    required super.createdAt,
    required super.updatedAt,
  });

  factory SellerMemberModel.fromJson(Map<String, dynamic> json) {
    // Parse custom permissions from JSON list
    Set<Permission>? customPermissions;
    if (json['custom_permissions'] != null) {
      final permList = json['custom_permissions'] as List;
      customPermissions = permList
          .map((p) => Permission.fromString(p as String))
          .toSet();
    }

    return SellerMemberModel(
      id: json['id'] as String,
      sellerProfileId: json['seller_profile_id'] as String,
      userId: json['user_id'] as String,
      role: MemberRole.fromString(json['role'] as String? ?? 'viewer'),
      customPermissions: customPermissions,
      invitedBy: json['invited_by'] as String?,
      invitedAt: json['invited_at'] != null
          ? DateTime.parse(json['invited_at'] as String)
          : null,
      joinedAt: json['joined_at'] != null
          ? DateTime.parse(json['joined_at'] as String)
          : null,
      isActive: json['is_active'] as bool? ?? true,
      memberName: json['member_name'] as String? ??
          json['profiles']?['full_name'] as String? ??
          'Noma\'lum',
      memberEmail: json['member_email'] as String? ??
          json['profiles']?['email'] as String?,
      memberAvatarUrl: json['member_avatar_url'] as String? ??
          json['profiles']?['avatar_url'] as String?,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : DateTime.now(),
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'seller_profile_id': sellerProfileId,
      'user_id': userId,
      'role': role.value,
      if (customPermissions != null)
        'custom_permissions':
            customPermissions!.map((p) => p.value).toList(),
      'invited_by': invitedBy,
      'invited_at': invitedAt?.toIso8601String(),
      'joined_at': joinedAt?.toIso8601String(),
      'is_active': isActive,
      'member_name': memberName,
      'member_email': memberEmail,
      'member_avatar_url': memberAvatarUrl,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  /// Create insert payload (without id, created_at, updated_at — auto-generated by DB)
  Map<String, dynamic> toInsertJson() {
    return {
      'seller_profile_id': sellerProfileId,
      'user_id': userId,
      'role': role.value,
      if (customPermissions != null)
        'custom_permissions':
            customPermissions!.map((p) => p.value).toList(),
      'invited_by': invitedBy,
      'invited_at': invitedAt?.toIso8601String(),
      'joined_at': joinedAt?.toIso8601String(),
      'is_active': isActive,
      'member_name': memberName,
      'member_email': memberEmail,
      'member_avatar_url': memberAvatarUrl,
    };
  }

  factory SellerMemberModel.fromEntity(SellerMember entity) {
    return SellerMemberModel(
      id: entity.id,
      sellerProfileId: entity.sellerProfileId,
      userId: entity.userId,
      role: entity.role,
      customPermissions: entity.customPermissions,
      invitedBy: entity.invitedBy,
      invitedAt: entity.invitedAt,
      joinedAt: entity.joinedAt,
      isActive: entity.isActive,
      memberName: entity.memberName,
      memberEmail: entity.memberEmail,
      memberAvatarUrl: entity.memberAvatarUrl,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
    );
  }
}
