import '../../../../core/services/permission_service.dart';
import '../../domain/entities/seller_invitation.dart';

/// Seller invitation model with JSON serialization

class SellerInvitationModel extends SellerInvitation {
  const SellerInvitationModel({
    required super.id,
    required super.sellerProfileId,
    required super.email,
    required super.role,
    required super.invitedBy,
    required super.status,
    required super.token,
    required super.expiresAt,
    super.inviterName,
    super.inviterAvatarUrl,
    super.sellerName,
    required super.createdAt,
    required super.updatedAt,
  });

  factory SellerInvitationModel.fromJson(Map<String, dynamic> json) {
    return SellerInvitationModel(
      id: json['id'] as String,
      sellerProfileId: json['seller_profile_id'] as String,
      email: json['email'] as String,
      role: MemberRole.fromString(json['role'] as String? ?? 'viewer'),
      invitedBy: json['invited_by'] as String,
      status: InvitationStatus.fromString(
          json['status'] as String? ?? 'pending'),
      token: json['token'] as String? ?? '',
      expiresAt: json['expires_at'] != null
          ? DateTime.parse(json['expires_at'] as String)
          : DateTime.now().add(const Duration(days: 7)),
      inviterName: json['inviter']?['full_name'] as String?,
      inviterAvatarUrl: json['inviter']?['avatar_url'] as String?,
      sellerName: json['seller_profile']?['business_name'] as String?,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : DateTime.now(),
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'seller_profile_id': sellerProfileId,
      'email': email,
      'role': role.value,
      'invited_by': invitedBy,
      'status': status.value,
      'token': token,
      'expires_at': expiresAt.toIso8601String(),
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  /// Create insert payload (without id, created_at, updated_at — auto-generated by DB)
  Map<String, dynamic> toInsertJson() {
    return {
      'seller_profile_id': sellerProfileId,
      'email': email,
      'role': role.value,
      'invited_by': invitedBy,
      'status': status.value,
      'token': token,
      'expires_at': expiresAt.toIso8601String(),
    };
  }

  factory SellerInvitationModel.fromEntity(SellerInvitation entity) {
    return SellerInvitationModel(
      id: entity.id,
      sellerProfileId: entity.sellerProfileId,
      email: entity.email,
      role: entity.role,
      invitedBy: entity.invitedBy,
      status: entity.status,
      token: entity.token,
      expiresAt: entity.expiresAt,
      inviterName: entity.inviterName,
      inviterAvatarUrl: entity.inviterAvatarUrl,
      sellerName: entity.sellerName,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
    );
  }
}
